version: '3.8'
services:
  postgres:
    image: postgres:9.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pxl 
      POSTGRES_PASSWORD: password
      POSTGRES_DB: airtraffic

  flask-visualization:
    build: app/.
    ports:
      - "5000:5000"
    volumes:
      - ./app:/code
    environment:
      FLASK_ENV: development
    depends_on: 
     - postgres

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
    links:
    - "postgres:pgsql-server"